version: 2
updates:
  # Enable version updates for Terraform providers
  - package-ecosystem: "terraform"
    # Look for Terraform files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all updates into a single PR
    groups:
      terraform-providers:
        patterns:
          - "*"
    # Set a limit on the number of open PRs Dependabot can have
    open-pull-requests-limit: 5
    # Add labels to the PRs
    labels:
      - "dependencies"
      - "terraform"
