formatter: markdown

header-from: .header.md
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Examples

  ```hcl
  {{ include "examples/sentinel-local/main.tf" }}
  ```

  ```hcl
  {{ include "examples/opa-local/main.tf" }}
  ```

  {{ .Footer }}

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
